oktadev/okta-blog

- README.md
removes extra blank line in readme to trigger build
> reverts silly build trigger

- _source/_posts/2019-09-05-laravel-authentication.md
Fixing liquid template warnings.
> Fix warnings

- _source/_posts/2019-09-17-build-a-spring-boot-kotlin-app.md
> Add missing package name to kotlin post

- _source/_posts/2019-09-17-build-a-spring-boot-kotlin-app.md
> update spring-kotlin intro

- _source/_posts/2019-09-18-build-a-simple-dotnet-core-app-in-docker.md
https://docs.google.com/document/d/11lbGZhfzqI0U1XLRyEdaeMTvtbKfag8X3Xo3tuRAuGM/edit?pli=1#
> Charlie docker aspnetcore post

- _source/_posts/2018-02-06-build-user-registration-with-node-react-and-okta.md
These are changes to update one of Lee's posts. Unfortunately, I couldn't make the whole tutorial work, so I'm not sure we should merge this yet. We might want to wait until @leebrandt gets back.
Example app changes in https://github.com/oktadeveloper/okta-node-react-registration-example/pull/1.
> Update Node + React post to use latest versions

- _source/_posts/2019-09-19-nodejs-typescript.md
> Node.js + TypeScript post

- _source/_posts/2019-09-19-nodejs-typescript.md
Some tweaks to the post based on @mraible's review.
> tweaks to Node.js + TypeScript post

- _source/_posts/2019-09-23-tutorial-build-a-maven-plugin.md
> Added screencast, fixed tweet @refs

- package.json
It will now:
- Show future posts
- Automatically livereload pages when changes are made
> Modifying `npm start`.

- _source/_posts/2018-06-08-add-authentication-to-any-web-page-in-10-minutes.md
> Update 10m Web Page blog post to remove trusted origins section

- _source/_posts/2019-09-17-build-a-spring-boot-kotlin-app.md
> Fix curl command in Kotlin post

- _source/_posts/2019-10-30-java-oauth2.md
FYI... @bdemers Please make sure and QA contractor posts so this doesn't happen in the future.
> Fix code in Java + OAuth 2 post

- _source/_posts/2019-10-21-illustrated-guide-to-oauth-and-oidc.md
> add youtube video to illustrated guide post

- _source/_posts/2019-11-08-get-started-with-koa-for-node-apps.md
> adds koa.js post

- _source/_posts/2019-12-03-spring-boot-deploy-options.md
> spring-boot-deploy-options tabs to spaces

- _source/_posts/2019-11-27-graalvm-java-binaries.md
> remove rouge backtick

- _source/_posts/2019-12-16-semantic-versioning.adoc
> Semantic v2

- _source/_posts/2020-01-17-aws-athena-data-analysis-supplement.md
> small code fix

- _source/_posts/2020-01-17-aws-athena-data-analysis-supplement.md
> Fixed the RIGHT minor code bug

- _source/_posts/2020-01-23-pkce-oauth2-spring-boot.md
Live deploy: 
https://5e277aed0e60ca0008ab6391--okta-blog.netlify.com/blog/2020/01/23/pkce-oauth2-spring-boot
> PKCE Always Spring Boot

- _source/_posts/2020-01-06-crud-angular-9-spring-boot-2.adoc
Example app changes in https://github.com/oktadeveloper/okta-spring-boot-2-angular-9-example/pull/1.
> Update Angular + Spring Boot to Angular 9 RC11 and Spring Boot 2.2.4

- _source/_posts/2018-07-19-simple-crud-react-and-spring-boot.md
Fix in example app at https://github.com/oktadeveloper/okta-spring-boot-react-crud-example/pull/13.
> Fix code in React + Spring Boot CRUD Blog post

- _source/_posts/2020-02-26-build-a-secure-nestjs-api-with-postgres.md
> nestjs post

- _source/_posts/2019-05-22-java-microservices-spring-boot-spring-cloud.adoc
Example updated at https://github.com/oktadeveloper/java-microservices-examples/pull/7.
> Update Spring Boot + Cloud post to use SB 2.2.5

- _source/_includes/head.html
This commit makes it possible to use the Google Analytics API, even though we're loading GA using Google Tag Manager.
> Adding code to expose the 'ga' library.

- _source/_posts/2020-03-13-developers-guide-on-reporting-vulnerabilities.adoc
> add video to how-to-report-vulns post

- _source/_posts/2020-02-26-build-a-secure-nestjs-api-with-postgres.md
> fixes yml and code formatting

- _source/_layouts/blog_index.html
- _source/_posts/2020-04-09-whats-new-with-oauth-and-oidc.md
also adds a `summary` property in the YAML header to customize the text that appears on the home page
> add blog post for today's video

- _source/_assets/css/okta/components/_AuthorPage.scss
- _source/_data/authors.yml
- _source/_layouts/author.html
- _source/_plugins/data_page_generator.rb
also fix page title on author pages
> add bio field to author pages

- _source/_includes/head.html
> Adding canonical links on every page, not just blog pages.

- _source/_posts/2015-06-11-trustpage.md
- _source/_posts/2015-12-02-tls-client-authentication-for-services.md
- _source/_posts/2017-06-21-what-the-heck-is-oauth.md
- _source/_posts/2017-07-25-oidc-primer-part-1.md
- _source/_posts/2017-07-25-oidc-primer-part-2.md
- _source/_posts/2017-08-01-oidc-primer-part-3.md
- _source/_posts/2017-08-17-why-jwts-suck-as-session-tokens.md
- _source/_posts/2018-02-27-a-breakdown-of-the-new-saml-authentication-bypass-vulnerability.md
- _source/_posts/2018-04-10-oauth-authorization-code-grant-type.md
- _source/_posts/2018-04-17-webauthn-developers-guide-to-whats-on-the-horizon.md
- _source/_posts/2018-05-23-announcing-passprotect-proactive-web-security.md
- _source/_posts/2018-05-24-what-is-the-oauth2-implicit-grant-type.md
- _source/_posts/2018-06-20-what-happens-if-your-jwt-is-stolen.md
- _source/_posts/2018-06-29-what-is-the-oauth2-password-grant.md
- _source/_posts/2018-10-22-stolen-access-tokens.md
- _source/_posts/2019-01-22-oauth-api-keys-arent-safe-in-mobile-apps.md
- _source/_posts/2019-01-23-nobody-cares-about-oauth-or-openid-connect.md
- _source/_posts/2019-05-01-is-the-oauth-implicit-flow-dead.md
- _source/_posts/2019-06-04-what-the-heck-is-sign-in-with-apple.md
- _source/_posts/2019-07-25-the-hardest-thing-about-data-encryption.md
- _source/_posts/2019-07-29-hashing-techniques-for-password-storage.md
- _source/_posts/2019-08-01-secure-applications-with-certificate-pinning.md
- _source/_posts/2019-08-22-okta-authjs-pkce.md
- _source/_posts/2019-08-26-combat-side-channel-attacks-with-corb.md
- _source/_posts/2019-09-04-securing-rest-apis.md
- _source/_posts/2019-09-12-why-public-key-cryptography-matters.md
- _source/_posts/2019-10-17-a-thorough-introduction-to-paseto.md
- _source/_posts/2019-10-23-dangers-of-self-signed-certs.md
- _source/_posts/2019-12-19-multi-factor-authentication-sucks.md
- _source/_posts/2020-03-13-developers-guide-on-reporting-vulnerabilities.adoc
Adding some cross-linkage to our new security site.
> Adding linkage to the new sec.okta.com domain.

- _source/_posts/2020-03-16-react-styled-components.md
Example app updates in https://github.com/oktadeveloper/okta-react-styled-components-example/pull/2.
> Update React Styled Components to remove /implicit

- _source/_posts/2019-03-12-oauth2-spring-security-guide.md
Example app updates in https://github.com/oktadeveloper/okta-spring-boot-authz-server-example/pull/3.
> Update Authz server example to use Spring Boot 2.2.7

- _source/_posts/2020-01-09-java-rest-api-showdown.md
Example app updates in https://github.com/oktadeveloper/okta-java-rest-api-comparison-example/pull/5.
> Upgrade framework versions in Java API Showdown

- _source/_posts/2019-06-24-ionic-4-angular-spring-boot-jhipster.adoc
Example app changes at https://github.com/oktadeveloper/okta-ionic4-jhipster-example/pull/10.
> Remove /implicit from Ionic + JHipster post

- _source/_posts/2020-06-01-node-postgres-weight-tracker.md
> adds youtube video to post

- _source/_posts/2020-06-01-node-postgres-weight-tracker.md
> adds missing step to tutorial

- _source/_posts/2020-07-10-quickly-build-apps-with-sailsjs.md
> Fix double curly brace issue with raw/endraw

- _source/_posts/2020-07-22-identity-first-class-citizen.md
> Initial load of identity post

- _source/_posts/2019-11-22-node-postgres-simple-webapp.md
> Added repo link to blog post.

- Dockerfile
> updates docker container to use node.js 14

- _source/_posts/2020-01-13-kotlin-react-crud.md
Example app changes in https://github.com/oktadeveloper/okta-kotlin-react-crud-example/pull/5.
> Update Spring Boot + React to latest SDKs

- _source/_posts/2020-01-13-kotlin-react-crud.md
Fixes invalid link in https://github.com/oktadeveloper/okta-blog/pull/369.
> Fix link to PR in Spring Boot + React post

- _source/_posts/2020-08-24-simple-graphql-csharp.md
> fixing repo and removed one Learn More link

- _source/_posts/2020-08-28-talks-at-disclosure.md
> Disclosure Post

- _source/_posts/2019-08-28-reactive-microservices-spring-cloud-gateway.adoc
Example app changes in https://github.com/oktadeveloper/java-microservices-examples/pull/9.
> Fix CORS configuration in Spring Cloud Gateway post

- _source/_posts/2020-08-07-spring-boot-remote-vs-local-tokens.md
> Add video to Spring Boot jwt + opaque access token post

- _source/_posts/2020-09-23-secure-pii-ef-core-dotnet.md
Made a minor fix, testing with Randall
> Fixing wording in article

- _source/_posts/2020-10-14-spring-security-saml-database-authentication.md
> TESTING PR MERGES

- _source/_posts/2020-10-28-secure-web-apps-websockets-nodejs.md
> makes links relative

- _source/_posts/2020-11-23-quick-graphql-react-app.md
> relative read more post

- _source/_posts/2020-12-15-okta-linux-dotnet-server-support.md
> Greg's .NET Core SameSite + OAuth Apps on Linux post

- _source/_posts/2020-08-07-spring-boot-remote-vs-local-tokens.md
> Update jwt-opaque post to work with the latest Spring Boot 2.4

- .github/workflows/scheduled-merge.yml
> Adding schedule support

- _source/_posts/2020-11-20-spring-data-jpa.md
Example app changes in https://github.com/oktadeveloper/okta-spring-data-jpa-example/pull/4.
> Upgrade Spring Data JPA post to Spring Boot 2.4.2

- _source/_posts/2019-09-30-java-quarkus-oidc.md
Example app changes in https://github.com/oktadeveloper/okta-quarkus-example/pull/3.
> Minor updates to java-quarkus-oidc to update to latest version of Quarkus

- _source/_posts/2018-03-21-dropwizard-oauth.md
- _source/_posts/2018-03-30-everything-you-need-to-know-about-the-twelve-factor-app.md
- _source/_posts/2018-06-07-static-sites-vs-cms.md
- _source/_posts/2019-10-15-performance-testing-with-apache-bench.md
- _source/_posts/2020-01-09-java-rest-api-showdown.md
- _source/_posts/2020-04-20-android-authentication.adoc
- _source/_posts/2020-07-20-easy-user-sync-hooks.md
```shell
egrep -l '[a-zA-Z]\.\.$' * | xargs -I {} sed -E -i '' 's/([a-zA-Z]\.)\.$/\1/' {}
```
> Fix errant lines that end in two fullstops (".")

- _source/_posts/2021-02-24-what-being-musician-taught-me.md
> Added video link to blog post

- _source/_posts/2021-01-08-graphql-apollo-react.md
> Add video to blog post

- _source/_posts/2021-01-08-graphql-apollo-react.md
- _source/_posts/2021-02-24-what-being-musician-taught-me.md
> Updating video URLs

- _source/_posts/2021-03-05-ultimate-guide-to-password-hashing-in-okta.md
This fixes an issue where assets aren't loaded from developer.okta.com
> Move Brython assets to my website

- _source/_posts/2018-07-06-secure-api-mulesoft.md
> Remove Mulesoft post video

- _source/_posts/2017-12-04-use-kong-gateway-to-centralize-authentication.md
> updated post with new youtube reference and update at the header

- _source/_posts/2021-03-26-use-kong-gateway-to-centralize-authentication.md
updating old post. minor changes.
> updated post and referred to new post from old one

- _source/_posts/2018-12-20-crud-app-with-python-flask-react.md
> Update code to get the access token

- _source/_assets/css/okta/components/_BlogPost.scss
Builds off the work from @emmanuelgonzalez-okta in https://github.com/oktadeveloper/okta-blog/pull/691.
> Fix links to anchors from TOC

- _source/_includes/footer.html
Updating the footer ASAP to reflect new support changes.
> Modifying blog footer to match updated support links.

- _source/_posts/2021-01-11-microprofile-graphql.md
> Update MicroProfile GraphQL post claims setup

- _source/_posts/2021-06-02-auth-code-flow-kong-connect.md
The old one had placeholder text in its intro.
> Update Kong Video

- _source/_posts/2021-06-07-session-mgmt-node.md
> Initial load of Node session mgmt post

- _source/_posts/2021-06-07-session-mgmt-node.md
> git trash in my learn more section removed

- _source/_includes/setup/cli.md
> Fix link to create an API token

- _source/_posts/2020-11-20-spring-data-jpa.md
Example app updates in https://github.com/oktadev/okta-spring-data-jpa-example/pull/5.
> Update Spring Data JPA post for Spring Boot 2.5

- _source/_posts/2021-06-11-introspection-flow-kong-konnect.md
Fixes links to other posts in https://developer.okta.com/blog/2021/06/11/introspection-flow-kong-konnect.
> Fix links in Kong Introspection post
